# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 21, 9, 44, 47, 466664, tzinfo=utc)),
        ),
    ]
