# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_auto_20161021_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 21, 9, 46, 59, 950911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='started',
            field=models.DateTimeField(),
        ),
    ]
