# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0009_auto_20161021_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 21, 13, 38, 3, 480892, tzinfo=utc)),
        ),
    ]
